### ISSUE TITLE
怎么没有.cpkt文件 

### ISSUE THREAD

**Issue by yanlei-wei** [RYC-98/GRA#1]
哥  没有.cpkt  预训练权重是自己要下载吗？

![weight_names](https://github.com/RYC-98/GRA/assets/153587532/57aa7a63-749c-41a0-9979-dd69314571ea)

**Comment by RYC-98** [comment]
。。。README里面写了权重下载的地址，也可以直接用这个链接：https://drive.google.com/drive/folders/10cFNVEhLpCatwECA6SPB-2g0q5zZyfaw
